manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
  projects:
    - name: eyelash_sofle
      url: https://github.com/MicheleYin/zmk-sofle
      revision: main
    - name: zmk
      remote: zmkfirmware
      revision: aed236f53fc2e6377293b3c6bd4a2eb3d97dc763
      import: app/west.yml
  self:
    path: config
