manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
  projects:
    - name: eyelash_sofle
      url: https://github.com/MicheleYin/zmk-sofle
      revision: main
    - name: zmk
      remote: zmkfirmware
      revision: 70536371a6b25a03e2d534cd88801284d3a8edb7
      import: app/west.yml
  self:
    path: config
