manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
  projects:
    - name: eyelash_sofle
      url: https://github.com/MicheleYin/zmk-sofle
      revision: main
    - name: zmk
      remote: zmkfirmware
      revision: 06b97d232cd8b577222133291e91badae206967d
      import: app/west.yml
  self:
    path: config
